-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggK4VDQoQFAoWanBz
DDQSPlllhACx9Tib39o9RNXt8POgCgYIKoZIzj0DAQehRANCAASNhBDEkmlpxA3c
ei8q5++PBIptrinyBGIAIdT2PyvBxYH//dfmR1SKN583aF7KPRvLrzDKtOinFYM2
MF4GpQ1i
-----END PRIVATE KEY-----